[Tue Feb 11 15:00:37 2020] [Out]: Args: ['G:/Code/QplayBubbles-Releaes/__main__.py', '1.5.0-pre5', '1_5_0_pre5', '16', '--debug']
[Tue Feb 11 15:00:37 2020] [Out]: Launcher Path: G:\
[Tue Feb 11 15:00:38 2020] [Out]: {'version': '1.5.0-pre5', 'versionDir': '1_5_0_pre5', 'build': 16, 'file': 'G:/Code/QplayBubbles-Releaes/__main__.py', 'debug': True}
[Tue Feb 11 15:00:38 2020] [Out]: ['.git', '.gitignore', '.idea', '.ropeproject', '.travis.yml', 'LICENSE', '__init__.py', '__main__.py', 'bubbles', 'config', 'data', 'lang', 'lib', 'logging.conf', 'logs', 'requirements.txt', 'slots', 'test', 'version.json', 'slots.old', 'test.py', 'TestFile.gpg', 'testfiles.py']
[Tue Feb 11 15:00:38 2020] [Out]: G:\Code\QplayBubbles-Releaes
[Tue Feb 11 15:00:38 2020] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}, 'height': 1, 'width': 1, 'middle-y': 1, 'middle-x': 1}
[Tue Feb 11 15:00:38 2020] [Err]: Traceback (most recent call last):
[Tue Feb 11 15:00:38 2020] [Err]:   File "G:/Code/QplayBubbles-Releaes/__main__.py", line 111, in <module>
[Tue Feb 11 15:00:38 2020] [Err]:     Main.Game(launcher_cfg)
[Tue Feb 11 15:00:38 2020] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 38, in __init__
[Tue Feb 11 15:00:38 2020] [Err]:     self.window = RootWindow(launcher_cfg, self.start_game)
[Tue Feb 11 15:00:38 2020] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\window.py", line 48, in __init__
[Tue Feb 11 15:00:38 2020] [Err]:     self.titleChoice = TitleMenu().get()
[Tue Feb 11 15:00:38 2020] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\title.py", line 53, in __init__
[Tue Feb 11 15:00:38 2020] [Err]:     self.background.start()
[Tue Feb 11 15:00:38 2020] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\title.py", line 127, in start
[Tue Feb 11 15:00:38 2020] [Err]:     a = seedint(self.seed, i, 0, 0, 5)
[Tue Feb 11 15:00:38 2020] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\utils\__init__.py", line 85, in seedint
[Tue Feb 11 15:00:38 2020] [Err]:     seed_x = seed.randint(0, x)
[Tue Feb 11 15:00:38 2020] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\random.py", line 222, in randint
[Tue Feb 11 15:00:38 2020] [Err]:     return self.randrange(a, b+1)
[Tue Feb 11 15:00:38 2020] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\random.py", line 200, in randrange
[Tue Feb 11 15:00:38 2020] [Err]:     raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
[Tue Feb 11 15:00:38 2020] [Err]: ValueError: empty range for randrange() (0,-1919, -1919)
