[Mon Nov 25 13:20:22 2019] [Out]: Args: ['G:/Code/QplayBubbles-Releaes/__main__.py', 'v1.5.1-pre5', 'v1_5_1_pre5', '16', '--debug']
[Mon Nov 25 13:20:22 2019] [Out]: Launcher Path: G:\
[Mon Nov 25 13:20:22 2019] [Out]: {'version': 'v1.5.1-pre5', 'versionDir': 'v1_5_1_pre5', 'build': 16, 'file': 'G:/Code/QplayBubbles-Releaes/__main__.py', 'debug': True}
[Mon Nov 25 13:20:22 2019] [Out]: ['.git', '.gitignore', '.idea', '.ropeproject', '.travis.yml', 'bubbles', 'config', 'data', 'lang', 'lib', 'LICENSE', 'logging.conf', 'logs', 'requirements.txt', 'slots', 'slots.old', 'test', 'version.json', '__init__.py', '__main__.py']
[Mon Nov 25 13:20:22 2019] [Out]: G:\Code\QplayBubbles-Releaes
[Mon Nov 25 13:20:22 2019] [Out]: {'bubble': {'chance': 10, 'max-radius': 30, 'min-radius': 21, 'max-speed': 4.8, 'base-speed': 4.8, 'screen-gap': 100}, 'game': {'level-score': 10000, 'time-limit': 90, 'pause': False, 'resolution': '1920x1080', 'ship-radius': 15, 'ship-speed': 10, 'fullscreen': True, 'language': 'en'}, 'font': {'family': 'helvetica', 'size': -9}, 'height': 1, 'width': 1, 'middle-y': 1, 'middle-x': 1}
[Mon Nov 25 13:20:23 2019] [Out]: Object: {'LastPlayedOn': {'build': '16'}}
[Mon Nov 25 13:20:23 2019] [Out]: Keys: ['LastPlayedOn']
[Mon Nov 25 13:20:23 2019] [Out]: Key: LastPlayedOn | Value: {'build': '16'}
[Mon Nov 25 13:20:23 2019] [Out]: Object: {'build': '16'}
[Mon Nov 25 13:20:23 2019] [Out]: Keys: ['build']
[Mon Nov 25 13:20:23 2019] [Out]: Key: build | Value: 16
[Mon Nov 25 13:20:23 2019] [Out]: {'LastPlayedOn': <lib.utils.dict2class.<locals>.DictClass object at 0x000001FCEC095F88>}
[Mon Nov 25 13:20:23 2019] [Out]: Object: {'LastPlayedOn': {'build': 16, 'version': 'v1.5.1-pre5', 'version-dir': 'v1_5_1_pre5'}, 'seed': 123456}
[Mon Nov 25 13:20:23 2019] [Out]: Keys: ['LastPlayedOn', 'seed']
[Mon Nov 25 13:20:23 2019] [Out]: Key: LastPlayedOn | Value: {'build': 16, 'version': 'v1.5.1-pre5', 'version-dir': 'v1_5_1_pre5'}
[Mon Nov 25 13:20:23 2019] [Out]: Object: {'build': 16, 'version': 'v1.5.1-pre5', 'version-dir': 'v1_5_1_pre5'}
[Mon Nov 25 13:20:23 2019] [Out]: Keys: ['build', 'version', 'version-dir']
[Mon Nov 25 13:20:23 2019] [Out]: Key: build | Value: 16
[Mon Nov 25 13:20:23 2019] [Out]: Key: version | Value: v1.5.1-pre5
[Mon Nov 25 13:20:23 2019] [Out]: Key: version-dir | Value: v1_5_1_pre5
[Mon Nov 25 13:20:23 2019] [Out]: Key: seed | Value: 123456
[Mon Nov 25 13:20:23 2019] [Out]: {'LastPlayedOn': <lib.utils.dict2class.<locals>.DictClass object at 0x000001FCEDB8BB88>, 'seed': 123456}
[Mon Nov 25 13:20:24 2019] [Out]: [SelectCanvas]: CLICK!
[Mon Nov 25 13:20:24 2019] [Out]: event.widget.__dict__: {'widgetName': 'canvas', 'master': <tkinter.Frame object .!frame3.!frame.!frame.!frame2>, 'tk': <threadsafe_tkinter.TkWrapper object at 0x000001FCEC6979C8>, '_name': '!canvas', '_w': '.!frame3.!frame.!frame.!frame2.!canvas', 'children': {}, '_tclCommands': ['2185831704392<lambda>'], 'build': 16}
[Mon Nov 25 13:20:24 2019] [Out]: event.widget.master.grid_info(): {'in': <tkinter.Frame object .!frame3.!frame.!frame>, 'column': 0, 'row': 1, 'columnspan': 1, 'rowspan': 1, 'ipadx': 0, 'ipady': 0, 'padx': 0, 'pady': 0, 'sticky': ''}
[Mon Nov 25 13:20:24 2019] [Out]: [SelectCanvas]: Row 1
[Mon Nov 25 13:20:26 2019] [Out]: Running Save Index: 1 
[Mon Nov 25 13:20:26 2019] [Out]: [SaveLoading]: Loading Save Test!!!
[Mon Nov 25 13:20:26 2019] [Out]: [SaveLoading]: Build of Save is 16
[Mon Nov 25 13:20:26 2019] [Out]: Game Stating
[Mon Nov 25 13:20:26 2019] [Out]: [Game]: Starting XboxController
[Mon Nov 25 13:20:26 2019] [Out]: [Game]: Started XboxController
[Mon Nov 25 13:20:26 2019] [Out]: 5
[Mon Nov 25 13:20:26 2019] [Out]: Key-bindings binded to 'move_ship'
[Mon Nov 25 13:20:27 2019] [Err]: Bubbel-ID lijst is gelijk aan lengte nul.
[Mon Nov 25 13:20:27 2019] [Err]: Bubble-actie lijst is gelijk aan lengte nul.
[Mon Nov 25 13:20:27 2019] [Err]: Bubbel-snelheid lijst is gelijk aan lengte nul.
[Mon Nov 25 13:20:27 2019] [Out]: {DEBUG}: Stats after Restore at line(s) 1412 - 1415:
[Mon Nov 25 13:20:27 2019] [Out]: {DEBUG}: BUBBLES | {'active': 0}
[Mon Nov 25 13:20:27 2019] [Out]: {DEBUG}: Stats after Start Bubble Generation at line(s) 1417 - 1412:
[Mon Nov 25 13:20:27 2019] [Out]: {DEBUG}: BUBBLES | {'active': 0}
[Mon Nov 25 13:20:27 2019] [Out]: .
[Mon Nov 25 13:20:27 2019] [Out]: [XboxController]: Starting Daemons
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-22:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-5:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-24:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-3:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-23:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-11:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-26:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-28:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-13:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-15:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-27:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-9:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-25:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-17:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-14:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-30:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-12:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-31:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-33:
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-32:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-16:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-6:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-34:
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-29:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-10:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-21:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-20:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-35:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-38:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-37:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-36:
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-18:
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-19:
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]:     self.run()
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anac[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]:     self.run()
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-40:
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-8:
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-7:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-41:
[Mon Nov 25 13:20:27 2019] [Err]:     self.run()
[Mon Nov 25 13:20:27 2019] [Err]:     self.run()
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]: Exception in thread Thread-39:
[Mon Nov 25 13:20:27 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:27 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-42:
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-44:
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
strap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-45:
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-48:
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-47:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-46:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-43:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-50:
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-52:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-54:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-55:
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-56:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-53:
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-57:
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-58:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-51:
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-59:
Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-61:
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
\lib\Main.py", line 604, in <lambda>
run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thr[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-62:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-63:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-68:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-67:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-66:
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-69:
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-65:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-70:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-72:
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-73:
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-74:
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-76:
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
onda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-75:
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-77:
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-71:
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-78:
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-79:
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-81:
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-80:
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-82:
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
des")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-86:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
x in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
._kwargs)
y", line 625, in xMovement
un
strap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
\Main.py", line 566, in <lambda>
es
[Mon Nov 25 13:[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
e 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
t()
-id"])):
     not[[Mon Nov 25 13:20:28 2019] [Err[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
dex in range(len(ge[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
019] [Err]:   Fi[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()

[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-88:
):
onda3\lib\threading.py", line 870, in run
strap_inner
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-85:
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-87:
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-83:
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-89:
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:28 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:28 2019] [Err]: Exception in thread Thread-91:
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'window'
bda: self.move_bubbles()).start()
[Mon Nov 25 13:20:28 2019] [Err]: KeyError: 'bub-id'
yBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:28 2019] [Err]:     self.run()
[Mon Nov 25 13:20:28 2019] [Err]: 
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:28 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:28 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-92:
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-94:
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-95:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-93:
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
a3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _[Mon Nov[Mon Nov 25 13:20:29 2019] [Err]: KeyError[Mon Nov 25 13:20:29 2019] [Err]: 
ine 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-96:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-99:
eaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-97:
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-103:
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-100:
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-98:
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-104:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-102:
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-105:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-108:
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-109:
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-106:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-110:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-111:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-107:
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
elf._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-114:
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-113:
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-112:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-116:
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-117:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-118:
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-120:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-121:
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-115:
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-119:
naconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
 range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-123:
:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-122:
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-125:
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-126:
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-124:
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-128:
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-130:
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
b\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-127:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-129:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-132:
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-131:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-133:
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-137:
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-134:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-135:
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'bub-id'
yBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-136:
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes[Mon Nov 25 13:20:2[Mon Nov 25 13:20:29 20[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-139:
n move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-141:
[Mon Nov 25 13:20:29 2019] [Err]: 
yError: 'bub-id'
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-140:
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-142:
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-138:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:29 2019] [Err]:     self.run()
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-143:
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:29 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:29 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:29 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:29 2019] [Err]: 
[Mon Nov 25 13:20:29 2019] [Err]: Exception in thread Thread-145:
[Mon Nov 25 13:20:29 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-146:
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-147:
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-144:
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-149:
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-148:
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-150:
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-154:
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-155:
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
 lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-152:
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-153:
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-157:
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-151:
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-156:
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: 
File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-159:
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-161:
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-158:
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-160:
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-163:
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
b\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-162:
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
tart()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-164:
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:   [Mon Nov 25 13:20:30 2019] [Err]:     self.run()
\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-167:
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-166:
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: 
File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-165:
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-170:
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
a3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
es
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-171:
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
w'
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-172:
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-173:
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-176:
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-174:
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-178:
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-181:
[Mon Nov 25 13:20:30 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:30 2019] [Err]:     self.run()
[Mon Nov 25 13:20:30 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-179:
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-177:
[Mon Nov 25 13:20:30 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:30 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: 
[Mon Nov 25 13:20:30 2019] [Err]: Exception in thread Thread-175:
[Mon Nov 25 13:20:30 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:30 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-180:
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-183:
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-185:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: 
File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-187:
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-182:
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-190:
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-186:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-191:
elf._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
yBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
QplayBubbles-Releaes\lib\Main.p[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: 
aceback (most recent call last):
tat("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-188:
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: 
yError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
ead Thread-193:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-189:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-192:
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-194:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.p[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-197:
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-199:
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-198:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-196:
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Rele[Mon Nov 25 13:20:31 2019] [Err]:   File[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._a[Mon Nov 25 1[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-202:
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-204:
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-201:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-206:
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-205:
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-203:
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-211:
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-209:
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-210:
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-208:
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-212:
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
:
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-213:
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-215:
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
bda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-214:
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-219:
[Mon Nov 25 13:20:31 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-218:
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: 
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-221:
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]:     self.run()
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self._movent()).start()
[Mon Nov 25 13:20:31 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:31 2019] [Err]: Exception in thread Thread-216:
[Mon Nov 25 13:20:31 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:31 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:31 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:31 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-223:
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-224:
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 814, in <lambda>
[Mon Nov 25 13:20:32 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:32 2019] [Err]:     not get_stats("Modes")["window"]):
[Mon Nov 25 13:20:32 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-225:
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 604, in <lambda>
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]:     for bub_index in range(len(get_stats("Bubbles")["bub-id"])):
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]:     Thread(None, lambda: self.move_bubbles()).start()
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:     not get_stats("Modes")["window"]):
les()).start()
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-222:
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'window'
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 566, in <lambda>
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-228:
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-227:
[Mon Nov 25 13:20:32 2019] [Err]:     self.run()
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 795, in move_bubbles
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]:     self._target(*self._args, **self._kwargs)
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 202, in _movent
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]: 
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:     Thread(None, lambda: self.xMovement()).start()
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]: KeyError: 'bub-id'
[Mon Nov 25 13:20:32 2019] [Err]: Exception in thread Thread-226:
[Mon Nov 25 13:20:32 2019] [Err]:   File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]:   File "G:\Code\QplayBubbles-Releaes\lib\Main.py", line 625, in xMovement
[Mon Nov 25 13:20:32 2019] [Err]: Traceback (most recent call last):
[Mon Nov 25 13:20:32 2019] [Err]: 
File "C:\Users\LAB-medewerker\Anaconda3\lib\threading.py", line 870, in run
